version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: nock
    versions:
    - 13.0.10
  - dependency-name: morgan
    versions:
    - 1.10.0
  - dependency-name: debug
    versions:
    - 4.3.1
  - dependency-name: http-errors
    versions:
    - 1.8.0
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: nodemon
    versions:
    - 2.0.7
  - dependency-name: "@elastic/elasticsearch"
    versions:
    - 7.11.0
