# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

name: Build

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-node@v2.1.5
      with:
        node-version: '12.x'

    - uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node
          ${{ runner.OS }}-

    - run: npm ci

    - name: check
      run: find . -name "*.js" -not -path "./node_modules/*" -exec node --check {} \;

    - run: npm run test

    - name: Deploy to search.developer.stage.swedbankpay.com
      if: github.ref == 'refs/heads/develop'
      uses: azure/webapps-deploy@v2
      with:
        app-name: developer-portal-search-stage
        slot-name: production
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1043a8e4641b4abcbfda30028fb8c291 }}
        package: .

    - name: Deploy to search.developer.swedbankpay.com
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v2
      with:
        app-name: developer-portal-search-prod
        slot-name: production
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_39f808f697834877a436c3dbe8c2b3d4 }}
        package: .
